In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

dataset=pd.read_csv('Data.csv')
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan , strategy='mean')
imputer.fit(x[: , 1:3])
x[: , 1:3]=imputer.transform(x[: , 1:3])

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
x=np.array(ct.fit_transform(x))

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)



In [ ]:
splitting dataset into test set and training set

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y, train_size=0.2,random_state=1)

In [8]:
print(x_train)

[[0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [9]:
print(x_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]]


In [10]:
print(y_train)

[0 1]


In [11]:
print(y_test)

[0 1 0 1 0 0 1 1]


In [ ]:
APPLY FEATURE SCALING ONLY AFTER SPLITTING DATASET

Xstd = x-mean(x)              Xnormalised = x-min(x)
      -----------                          ------------
    standard devis(x)                       max(x)-min(x)
    
    X std values from -3 to +3
    X norm values from 0 to 1
    
    Standardization would work for all time.

In [12]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train[:, 3:]=sc.fit_transform(x_train[:, 3:])
x_test[:, 3:]=sc.transform(x_test[:, 3:])

In [13]:
print(x_train)

[[0.0 1.0 0.0 1.0 1.0]
 [1.0 0.0 0.0 -1.0 -1.0]]


In [14]:
print(x_test)

[[0.0 1.0 0.0 -1.6666666666666667 -1.32]
 [1.0 0.0 0.0 -0.7333333333333333 -0.28]
 [0.0 0.0 1.0 -0.4962962962962962 -1.48]
 [0.0 1.0 0.0 -0.3333333333333333 -0.5377777777777775]
 [1.0 0.0 0.0 0.2 0.12]
 [0.0 0.0 1.0 -0.6 -0.76]
 [0.0 0.0 1.0 -2.066666666666667 -1.8]
 [1.0 0.0 0.0 0.7333333333333333 0.68]]
